# Generated by Django 4.0.3 on 2022-03-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('antigüedad', models.DateField(max_length=50)),
                ('desempleado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=40)),
                ('desempleado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('marketing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profesionales.marketing')),
                ('tarea_asignada', models.CharField(max_length=35)),
                ('fecha_entrega', models.DateTimeField(max_length=10)),
            ],
            bases=('profesionales.marketing',),
        ),
        migrations.CreateModel(
            name='Permanente',
            fields=[
                ('marketing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profesionales.marketing')),
                ('sueldo_aportes', models.IntegerField(max_length=1000)),
            ],
            bases=('profesionales.marketing',),
        ),
    ]
